package com.cts.pharmaTrack.module.notification.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * An in-app notification raised for a user (adverse-event escalation, batch QC
 * hold, cold chain breach, CAPA overdue, regulatory deadline, etc.).
 *
 * <p>Maps to the {@code notification} table. The primary key
 * {@code notificationId} is generated by the server as an incrementing numeric id.
 */
@Entity
@Table(name = "notification")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //@Column(name = "notificationId", updatable = false, nullable = false, columnDefinition = "BIGINT AUTO_INCREMENT")
    private Long notificationId;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "userId", nullable = false)
    private UserDetails user;

    public String getUserId() {
        return user != null ? String.valueOf(user.getUserId()) : null;
    }

    @Column(name = "message", length = 2000)
    private String message;

    /** Trial / Batch / ColdChain / Deviation / Regulatory */
    @Column(name = "category", length = 20)
    private String category;

    /** Unread / Read / Dismissed */
    @Column(name = "status", length = 20)
    private String status;

    @Column(name = "createdDate")
    private LocalDateTime createdDate;
}
