package com.cts.pharmaTrack.module.notification.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

/**
 * Inbound payload for creating or updating a notification.
 * Notification id is generated by the server on creation.
 */
@Getter
@Setter
public class NotificationRequest {

    @NotBlank(message = "userId is required")
    private String userId;

    @NotBlank(message = "message is required")
    private String message;

    private String category;

    private String status;
}
