package com.cts.pharmaTrack.module.notification.service;

import com.cts.pharmaTrack.common.exception.ResourceNotFoundException;
import com.cts.pharmaTrack.module.notification.dto.NotificationRequest;
import com.cts.pharmaTrack.module.notification.dto.NotificationResponse;
import com.cts.pharmaTrack.module.notification.entity.Notification;
import com.cts.pharmaTrack.module.notification.entity.UserDetails;
import com.cts.pharmaTrack.module.notification.repository.NotificationRepository;
import com.cts.pharmaTrack.module.notification.repository.UserDetailsRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.util.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Business logic for in-app notifications: creation, lookup, status changes
 * (read / dismissed) and deletion. The primary key {@code notificationId} is
 * generated by the server as an incrementing numeric id; {@code createdDate} is stamped
 * by the server on creation.
 */
@Service
@RequiredArgsConstructor
@Transactional
public class NotificationService {

    private static final Logger logger = LoggerFactory.getLogger(NotificationService.class);
    private static final String STATUS_UNREAD = "Unread";
    private static final String STATUS_READ = "Read";
    private static final String STATUS_DISMISSED = "Dismissed";

    private final NotificationRepository notificationRepository;
    private final UserDetailsRepository userDetailsRepository;

    public NotificationResponse create(NotificationRequest request) {
        logger.info("Executing create for userId: {}", request.getUserId());
        Integer uid = Integer.parseInt(request.getUserId());
        UserDetails user = userDetailsRepository.findById(uid)
                .orElseThrow(() -> new ResourceNotFoundException("User not found with ID: " + uid));
        Notification notification = new Notification();
        notification.setUser(user);
        notification.setMessage(request.getMessage());
        notification.setCategory(request.getCategory());
        notification.setStatus(StringUtils.hasText(request.getStatus())
                ? request.getStatus() : STATUS_UNREAD);
        notification.setCreatedDate(LocalDateTime.now());
        return toResponse(notificationRepository.save(notification));
    }

    @Transactional(readOnly = true)
    public List<NotificationResponse> getAll() {
        logger.info("Executing getAll");
        List<Notification> notifications = notificationRepository.findAll();
        if (notifications.isEmpty()) {
            throw new ResourceNotFoundException("No notifications found");
        }
        return notifications.stream().map(this::toResponse).toList();
    }

    @Transactional(readOnly = true)
    public NotificationResponse getById(Long notificationId) {
        logger.info("Executing getById with notificationId: {}", notificationId);
        return toResponse(findOrThrow(notificationId));
    }

    @Transactional(readOnly = true)
    public List<NotificationResponse> getByUser(String userId) {
        logger.info("Executing getByUser with userId: {}", userId);
        return notificationRepository.findByUserUserId(Integer.parseInt(userId))
                .stream().map(this::toResponse).toList();
    }

    @Transactional(readOnly = true)
    public List<NotificationResponse> getByStatus(String userId, String status) {
        logger.info("Executing getByStatus with userId: {} status: {}", userId, status);
        return notificationRepository.findByUserUserIdAndStatus(Integer.parseInt(userId), status)
                .stream().map(this::toResponse).toList();
    }

    @Transactional(readOnly = true)
    public List<NotificationResponse> getByCategory(String userId, String category) {
        logger.info("Executing getByCategory with userId: {} category: {}", userId, category);
        return notificationRepository.findByUserUserIdAndCategory(Integer.parseInt(userId), category)
                .stream().map(this::toResponse).toList();
    }

    @Transactional(readOnly = true)
    public long getUnreadCount(String userId) {
        logger.info("Executing getUnreadCount for userId: {}", userId);
        return notificationRepository.countByUserUserIdAndStatus(Integer.parseInt(userId), STATUS_UNREAD);
    }

    public NotificationResponse markRead(Long notificationId) {
        logger.info("Executing markRead with notificationId: {}", notificationId);
        Notification notification = findOrThrow(notificationId);
        notification.setStatus(STATUS_READ);
        return toResponse(notificationRepository.save(notification));
    }

    public NotificationResponse markDismissed(Long notificationId) {
        logger.info("Executing markDismissed with notificationId: {}", notificationId);
        Notification notification = findOrThrow(notificationId);
        notification.setStatus(STATUS_DISMISSED);
        return toResponse(notificationRepository.save(notification));
    }

    public NotificationResponse updateStatus(Long notificationId, String status) {
        logger.info("Executing updateStatus with notificationId: {} status: {}", notificationId, status);
        Notification notification = findOrThrow(notificationId);
        notification.setStatus(status);
        return toResponse(notificationRepository.save(notification));
    }

    public void delete(Long notificationId) {
        logger.info("Executing delete with notificationId: {}", notificationId);
        Notification notification = findOrThrow(notificationId);
        notificationRepository.delete(notification);
    }

    private Notification findOrThrow(Long notificationId) {
        return notificationRepository.findById(notificationId)
                .orElseThrow(() -> new ResourceNotFoundException("Notification", notificationId));
    }

    private NotificationResponse toResponse(Notification n) {
        return new NotificationResponse(
                n.getNotificationId(),
                n.getUserId(),
                n.getMessage(),
                n.getCategory(),
                n.getStatus(),
                n.getCreatedDate());
    }
}
